name: covid_tracker
description: Covid 19 tracker
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async_redux: ^2.6.0
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

fonts:
  - family: ProductSans
    fonts:
      - asset: assets/fonts/product-sans/Product Sans Bold.ttf
        weight: 700
      - asset: assets/fonts/product-sans/Product Sans Regular.ttf
        weight: 400